name: unprejudiced
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - cudatoolkit=11.3
  - pytorch==1.10.0=py3.7_cuda11.3_cudnn8_0
  - transformers
  - colorama
  - scikit-learn
  - autopep8
  - wandb
